数字をタップしたらアラートが出るように
rikakohdafukuoh/swift01 pull request #6
Opened 2023-11-04 06:02 UTC by mutt5

# 目的
NumbersViewでListのitemをタップした際にアラートを表示させる

# やったこと
- itemをButtonに変更
- NavigationViewに.alertを追加
- ViewModelにshowAlertForを追加
- Viewのコードを分割

# 動作確認
https://github.com/rikakohdafukuoh/swift01/assets/69248950/85bd6e44-58c3-44b1-9819-ff074b01456d

2023-11-04 19:01 UTC, junkohda requested changes
NumbersViewでは、`func XXX: some View {}`という形で処理が分割されています。
正式な用語ではないのですが、これをマツリカでは「SwiftUIの関数切り出し」と呼んでいまして、禁じられた技術としています。
どういうことかというと、これはAppleの公式サイトには載ってない情報なのですが、iPhone12だと関数切り出しはバグを生み出してしまうのです。関数の処理結果が変な形でキャッシュされているのでバグるわけです。
ですので、関数切り出しをやめて「struct切り出し」でお願いします。詳しいやり方は個別のコメントに書きます。

2023-11-04 20:42 UTC, junkohda requested changes

2023-11-04 20:42 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +        .navigationTitle("Numbers")
`.navigationTitle("Numbers")`の宣言位置が間違っています。NavigationViewの修飾句として書いても機能しないです。正しくは、numbersListに対して使う必要があります。

```
        NavigationView {
            numbersList(viewModel: viewModel)
                .navigationTitle("Numbers")
        }
```

2023-11-04 20:42 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +private func numbersAlert(viewModel: NumbersViewModel) -> Alert {
関数の名前をもう少し良くしてみましょう。
この関数は NumbersViewModel の selectedNumber に基づいてアラートを生成しています。
そこで、`selectedNumberAlert `がいいと思います。

2023-11-04 20:42 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +        primaryButton: .default(Text("キャンセル")),      // 左ボタンの設定
ChatGPTのコメントが残っているので消してもらったほうがよいです。

2023-11-04 20:42 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +    return List(viewModel.numbers.indices, id: \.self) { index in
こんな感じのがいいと思います。

```
private struct NumbersListView: View {
    @ObservedObject var viewModel: NumbersViewModel
    
    var body: some View {
        List(viewModel.numbers.indices, id: \.self) { index in
            NumbersItemView(viewModel: viewModel, index: index)
                .onAppear {
                    if index == viewModel.numbers.count - 1 && !viewModel.isLoading {
                        viewModel.loadMoreData()
                    }
                }
        }
    }
}
```

2023-11-05 03:22 UTC, mutt5 commented
コメントにあった修正を行いました。

2023-11-05 03:27 UTC, mutt5 commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +        Alert(
Alertの切り出し方はこのやり方で大丈夫でしょうか？
またiOS15以上では構造体「Alert」によるアラートダイアログの実装方法は非推奨のようです。
https://developer.apple.com/documentation/swiftui/alert

2023-11-06 07:12 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +private struct SelectedNumberAlert {
前の指摘から漏れた内容になってしまいますが、`SelectedNumberAlert`自体がViewではなく単なるstructであるため、これは妥当な実装ではありません。どのように妥当でないかというと、SwiftUIのView以外で@ObservedObjectを使用することは良くないそうです。そこで、Alertの構築を別の構造体に分けるのをやめることを提案
します。

2023-11-06 07:23 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +private struct SelectedNumberAlert {
ソースはChatGPT

2023-11-06 07:24 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +        .alert(isPresented: $viewModel.showAlert) {
こういうのはどうでしょうか、後述のAlartの分離をやめたものです。
```
        .alert(isPresented: $viewModel.showAlert) {
            Alert(
                title: Text("アラート"),
                message: Text("\(viewModel.selectedNumber ?? 0)"),
                primaryButton: .default(Text("キャンセル")),
                secondaryButton: .default(Text("OK"), action: {
                    viewModel.toggleAlertFor(isShow: false, selectedNumber: nil)
                })
            )
        }
```

2023-11-06 07:25 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +                viewModel.showAlertFor(number: viewModel.numbers[index])
```
viewModel.toggleAlertFor(isShow: true, selectedNumber: viewModel.numbers[index])
```

2023-11-06 07:26 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +    func showAlertFor(number: Int) {
```
    func toggleAlertFor(isShow: Bool, selectedNumber: Int?) {
        self.showAlert = isShow
        self.selectedNumber = isShow ? selectedNumber : nil
    }
```

既存の実装だと、アラートでOKを押した後でもviewModel.selectedNumberに値がセットされたままなのでnilを入れてクリアするようにしてみるのはどうでしょうか

2023-11-06 07:28 UTC, junkohda requested changes
アラートについて、別structにするのではなく統合した方がよいそうです。
それに伴ってViewModelでのアラート表示のロジックを変更してみました。
参考にしてみてください。

2023-11-08 12:22 UTC, rikakohdafukuoh approved these changes
よさそう

2023-11-08 15:19 UTC, junkohda requested changes
private struct SelectedNumberAlertは解体し、var body: some View {}に直接書いてください。

2023-11-08 15:25 UTC, junkohda commented on HelloSwiftUI/HelloSwiftUI/Scenes/Number/NumbersView.swift
> +        .alert(isPresented: $viewModel.showAlert) {
```
    var body: some View {
        NavigationView {
            NumbersListView(viewModel: viewModel)
                .navigationTitle("Numbers")
        }
        .alert(isPresented: $viewModel.showAlert) {
            Alert(
                title: Text("アラート"),
                message: Text("\(viewModel.selectedNumber ?? 0)"),
                primaryButton: .default(Text("キャンセル")),
                secondaryButton: .default(Text("OK"))
            )
        }
    }
```

2023-11-08 15:28 UTC, junkohda approved these changes
alertの宣言位置だけ直してもらえればOKです。長期間お疲れ様でした。

2023-11-08 22:40 UTC, merged